dist: xenial
sudo: required
language: cpp

compiler:
    - gcc

before_install:
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - sudo apt-get update -qq
    - sudo apt-get install python3
    - pip3 install conan --user
    - conan profile new default --detect
    - conan profile update settings.compiler.libcxx=libstdc++11 default

script:
    - mkdir build && cd build
    - conan install ..
    - cmake .. -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release
    - cmake --build .
    - ctest -V
    
    
notifications:
  email:
    recipients:
      - tjhomoncik@gmail.com
    on_success: change
    on_failure: always
