sudo: required
language: cpp

compiler:
    - gcc

before_install:
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - sudo apt-get update -qq

install:
    - sudo apt install -y libncurses5-dev libncursesw5-dev
    - sudo apt-get install -qq g++-4.8
    - export CXX="g++-4.8"

script:
    - mkdir build && cd build
    - cmake ..
    - make
    
    
notifications:
  email:
    recipients:
      - tjhomoncik@gmail.com
    on_success: change
    on_failure: always
