sudo: required
language: cpp

env:
    - SETUP_CURSES="sudo apt remove -y libncursesw5-dev"
    - SETUP_CURSES="sudo apt install -y libncursesw5-dev"

compiler:
    - clang

before_install:
    - sudo apt update
    - eval "${SETUP_CURSES}"

script:
    - mkdir build && cd build
    - cmake ..
    - make
    
    
notifications:
  email:
    recipients:
      - tjhomoncik@gmail.com
    on_success: change
    on_failure: always
